### PR TITLE
Add list of open source funding platforms

### PR DESCRIPTION
**Pull request by timothyfcook**
In addition to the examples, folks should know about the awesome OS funding platforms that are out there. Paraphrased the descriptions directly from content on the site's About pages.

### CODE REVIEW

**Comment by whit537** [comment]
!m @timothyfcook 

Don't forget Liberapay!

```
* **[Liberapay](https://liberapay.com/),** provides a stable crowdfunded basic income to creators, enabling them to keep doing great work that benefits everyone
```

**Comment by MikeMcQuaid** [comment]
My concern is that this ends up becoming an always-expanding bullet list. Is there a way this could be refocused so that there's 2-3 and it's clear they are examples of different ways of solving the problem?

**Comment by bkeepers** [comment]
I agree with @MikeMcQuaid. The goal is to point people toward popular options. Patreon and Open Collective are already listed. We'd consider other examples if other platforms are more widely adopted.

**Comment by whit537** [comment]
I can't disagree.

Back to work, @timothyfcook!

**Comment by timothyfcook** [comment]
In the current version those read like examples of individual projects receiving corporate funding, not examples of platforms that anyone can use to host their project and get support from the community. 

Seems useful to point people to the tools, rather than individual projects. I expect the list isn't going to grow much beyond the above.

**Pull request closed without merging**
