### PR TITLE
Update legal.md

### PR DESCRIPTION
**Pull request by theo-armour**
fix broken link

### CODE REVIEW

**Comment by lee-dohm** [comment]
Unless I'm misunderstanding, the current link is correct and the suggested one would be broken [for the website.](https://opensource.guide/legal/) Are you seeing a broken link on the website?

**Comment by theo-armour** [comment]
@lee-dohm 

I was looking at the link here:

https://github.com/github/open-source-guide/blob/gh-pages/_articles/legal.md

Website should have priority over source code view.

Kindly delete my request.

**Comment by lee-dohm** [comment]
Thanks for the clarification :+1:

**Comment by bkeepers** [comment]
See #315 for work to get this working everywhere.

**Pull request closed without merging**
