### PR TITLE
adding a license-change blog as example

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by mlinksva** [comment]
@danielskatz thanks, good concrete example. The blog post linked doesn't contain the quote, does it? What is the source of the quote?

**Comment by danielskatz** [comment]
I made it up :)

Sorry, it was a bit hard to tell from the source how this was going to look, so I was trying to see this from another example in the file that I copied.  Now I see that this should be a quote.

As a quote, I suggest "we can do more to support goals of open science, open source, and build a stronger community by this relicensing" and I'll update the pull request with it.

**Comment by danielskatz** [comment]
ok, the pull request has been updated with the real quote

**Comment by mlinksva** [comment]
@danielskatz I don't think that works well as a pull quote. The others make sense on their own, little nuggets of wisdom, this one requires reading the context to figure out what "this" is. I :love: the example because it documents exactly what procedure they used and how they tracked it, but I don't think we have a place for it at the moment. If at some point we have a way of highlighting case studies this might be a good one. So thanks ✨  for the suggestion @danielskatz, but closing for now.

**Pull request closed without merging**
