### PR TITLE
Updated metrics.md

### PR DESCRIPTION
**Pull request by jsmanrique**
Added information, metrics and examples about "contributors demography", "contributors dependecy" and "diversity"

### CODE REVIEW

**Comment by lutzhorn** [comment]
How are all these metrics of any *practical* importance?

**Comment by jsmanrique** [comment]
"Contributors demography" helps community managers to understand if they are retaining talent/knowledge/people, and who are the people that stands in the community for longer periods.

"Contributors dependecy" metrics are usually used by third parties to check project sustainability. Generally, projects with higher APF (ASF Pony factor) and BEF (Bitergia Elephant factor) are considered more independent, since they are not controlled by an small group or a single company.

"Diversity" metrics show how inclusive the projects in terms, and "gender diversity" metrics are being currently used by OpenStack Foundation to give vissibility to women contributions. "Geographical diversity" helps community managers also on planning meetups or actions for new areas identified in the maps or timezones.

It might be my fault not starting by explaining these _practical examples_. Most of them come from my/our experience working with Open Source projects, so I've thought it migh be useful to share them.

**Comment by bkeepers** [comment]
Hey @jsmanrique, thanks for the PR. There's some good stuff here. I'd like to wait until @nayafia is back from vacation to discuss with her before proposing some tweaks.

**Comment by bkeepers** [comment]
Per https://github.com/github/open-source-guide/pull/324, we've updated the guidelines on adding content. 

> …please don't add links to things you or your employer have created as others will do so if they appreciate it.

There's some good content here that should probably still be considered, so feel free to open up a new pull request with this content.

**Pull request closed without merging**
