### PR TITLE
Ebook cover

### PR DESCRIPTION
**Pull request by bkeepers**
I took a crack at making an ebook cover based on the styles we're using for the [twitter cards](http://opensource.guide/assets/images/cards/default.png).

Via [Kindle direct publishing](https://kdp.amazon.com/help?topicId=A2J0TRG6OPX0VM):
> Kindle Direct Publishing currently accepts two types of files for cover images:
> - JPEG (JPEG / JPG)
> - TIFF (TIF / TIFF)
> Ideal dimensions for cover files are 2,560 x 1,600.

@sapegin it looks like [ebrew](https://www.npmjs.com/package/ebrew) doesn't support custom covers? 😢 

cc #316 

---

### CODE REVIEW

**Comment by aluciani** [comment]
Looks really good.

**Comment by sapegin** [comment]
> @sapegin it looks like ebrew doesn't support custom covers? 😢

Shouldn’t be [very hard](https://wiki.mobileread.com/wiki/Ebook_Covers) to add support but will require some work.

**Comment by sapegin** [comment]
Or maybe we should try something like [epub-gen](https://github.com/cyrilis/epub-gen) instead.

**Comment by bkeepers** [comment]
Closing for now until we have an ebook tool that supports covers.

**Pull request closed without merging**
