### PR TITLE
Fix margins so that cov-image does not touch ToC button

### PR DESCRIPTION
**Pull request by rixx**
Before:
2017-02-15-160206_934x403_scrot

After:
2017-02-15-160151_824x380_scrot

### CODE REVIEW

**Comment by numrut** [comment]
Hi, @rixx!

There is `.article-header.contribute .cover-img` in `https://opensource.guide/assets/css/index.css`. It would be better to use that one instead of simply `.cover-img` which is more general and affects all header images.

**Comment by rixx** [comment]
Huh? This is inside `.article-header.contribute {` …

**Comment by numrut** [comment]
Oh, sorry! You are right.
Good work!)

**Comment by clemencen** [comment]
Test Test Test

**Pull request merged**
